### ISSUE TITLE
ftdomdelegate complete breaking checklist

### ISSUE THREAD

**Issue by notlee** [Financial-Times/ftdomdelegate#98]
Origami plan to release major new versions of low level components, which remove technical debt from recent additions such as component branding, and implement more recent proposals such as adding a primary Sass mixin and removing custom classes from many Sass interfaces.

**steps**

- [x] Add MIGRATION.md
- [x] Add a [primary mixin](https://github.com/Financial-Times/origami-proposals/issues/6), removing other mixins where possible.
- [x] If a mixin is required which does not output a selector, e.g. for component composition, create an [oComponentContent](https://github.com/Financial-Times/origami-proposals/issues/14#issuecomment-485815788) mixin with options like the primary mixin (`Content` infers the mixin does not output selectors).
- [x] Replace methods to customise a component's style globally with a mixin [oComponentCustomise](https://github.com/Financial-Times/origami-proposals/issues/14#issuecomment-485815788) e.g. so a whitelabel user can customise the style of a primary o-buttons button.
- [x] Replace mixins which add new variations of a component with an [oComponentAddSomething](https://github.com/Financial-Times/origami-proposals/issues/14#issuecomment-485815788) mixin e.g. so a user may output a new o-buttons button, alongside primary buttons etc.
- [x] Remove [custom classnames](https://github.com/Financial-Times/origami-proposals/issues/4).
- [x] Use the `$system-code` variable for the `source` param in image service requests, error if not found, update obt to `^ 8.2.2` locally and in circleci config.
- [x] Remove existing semver ranges e.g. for o-brand and o-icons `"o-brand": ">=2.2.0 <4",`. We can't add new features to components used with a semver range without back-porting.
- [x] Use esm consistently over cjs module syntax.
- [x] Solve existing issues labeled "breaking" if possible.

**Comment by notlee** [comment]
This is done, to be released as part of the major cascade. See https://github.com/Financial-Times/ftdomdelegate/pull/100
